image: docker:20.10.14

check pep8 standards:
  image: python:3.10
  before_script:
    - /usr/local/bin/python -m pip install --upgrade pip
    - pip install yapf
  script:
    - linter_errors=$(yapf --diff --recursive src/spiir | wc -l | xargs test 0 -eq)
    - echo "$linter_errors"
    - if [ ! -z "$linter_errors" ]; then
      echo "Detected yapf formatting issues; please fix";
      exit 1; else echo "Yapf formatting is correct";
      exit 0; fi