image: docker:20.10.14

check pep8 standards:
  image: python:3.10
  before_script:
    - /usr/local/bin/python -m pip install --upgrade pip
    - pip install black
  script:
    - black --check --verbose --diff --color .
